name: invento
description: "Inventory Management System"

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_staggered_animations: ^1.1.1
  shimmer: ^3.0.0
  lottie: ^2.7.0
  auto_animated: ^3.2.0
  flutter_animate: ^4.5.0
  animations:
  logging: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  hive_generator: ^2.0.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
